services:
  ecommerce.gateway.api:
    image: ${DOCKER_REGISTRY-}ecommercegatewayapi
    container_name: ecommerce.gateway.api
    build:
      context: .
      dockerfile: eCommerce.Gateway.Api/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001 

  ecommerce.users.api:
    image: ${DOCKER_REGISTRY-}ecommerceusersapi
    container_name: ecommerce.users.api
    build:
      context: .
      dockerfile: eCommerce.Users.Api/Dockerfile
    ports:
      - 5100:5100
      - 5101:5101